name: Publish Echo Mcp Server to Dockerhub and GitHub Releases

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'  # Only trigger on tags with format like 1.2.3

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}
      hashes: ${{ steps.hash.outputs.HASHES }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
      - name: Update version in project file
        run: |
          # Extract the version from the tag
          VERSION=${{ steps.get_version.outputs.VERSION }}
          echo "Updating project version to $VERSION"
          
          # Use XML tool to update the version in the project file
          # This updates AssemblyVersion, FileVersion, and Version properties
          sed -i \
            -e "s/<AssemblyVersion>.*<\/AssemblyVersion>/<AssemblyVersion>$VERSION<\/AssemblyVersion>/g" \
            -e "s/<FileVersion>.*<\/FileVersion>/<FileVersion>$VERSION<\/FileVersion>/g" \
            -e "s/<Version>.*<\/Version>/<Version>$VERSION<\/Version>/g" \
            src/Core.Infrastructure.McpServer/Core.Infrastructure.McpServer.csproj
          
          # Show the updated fi